//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.21 at 01:21:52 PM AEST 
//

package com.gb.smartcomms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gb.fineos.generic.smartcomms.datamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReviewCase_QNAME = new QName("http://www.gallagherbasset.com.au/smartcommsappliance", "reviewCase");
    private final static QName _DocumentEnvelope_QNAME = new QName("http://www.gallagherbasset.com.au/smartcommsappliance", "documentEnvelope");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gb.fineos.generic.smartcomms.datamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReviewCase }
     * 
     */
    public ReviewCase createReviewCase() {
        return new ReviewCase();
    }

    public DocumentEnvelope createDocumentEnvelope() {
        return new DocumentEnvelope();
    }

    /**
     * Create an instance of {@link JobMessages }
     * 
     */
    public JobMessages createJobMessages() {
        return new JobMessages();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReviewCase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gallagherbasset.com.au/smartcommsappliance", name = "reviewCase")
    public JAXBElement<ReviewCase> createReviewCase(ReviewCase value) {
        return new JAXBElement<ReviewCase>(_ReviewCase_QNAME, ReviewCase.class, null, value);
    }

    @XmlElementDecl(namespace = "http://www.gallagherbasset.com.au/smartcommsappliance", name = "documentEnvelope")
    public JAXBElement<DocumentEnvelope> createDocumentEnvelope(DocumentEnvelope value) {
        return new JAXBElement<DocumentEnvelope>(_DocumentEnvelope_QNAME, DocumentEnvelope.class, null, value);
    }

}
