//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.21 at 01:21:52 PM AEST 
//


package com.gb.smartcomms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReviewCase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReviewCase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jobMessages" type="{http://www.gallagherbasset.com.au/smartcommsappliance}JobMessages" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReviewCase", namespace = "http://www.gallagherbasset.com.au/smartcommsappliance", propOrder = {
    "data",
    "jobMessages"
})
@XmlRootElement
public class ReviewCase {

    @XmlElement(required = true)
    protected String data;
    protected JobMessages jobMessages;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the jobMessages property.
     * 
     * @return
     *     possible object is
     *     {@link JobMessages }
     *     
     */
    public JobMessages getJobMessages() {
        return jobMessages;
    }

    /**
     * Sets the value of the jobMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobMessages }
     *     
     */
    public void setJobMessages(JobMessages value) {
        this.jobMessages = value;
    }

}
